name: run tests
on:
  push:
    tags-ignore:
      - "*"
    branches:
      - "**"
jobs:
  test:
    runs-on: ubuntu-latest
    concurrency: blazemeter_test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 8
      - name: Run maven tests
        run: mvn --batch-mode --no-transfer-progress clean install
#        env:
#          BZ_TOKEN: ${{ secrets.BZ_TOKEN }}
#          OCTOPERF_API_KEY: ${{ secrets.OCTOPERF_API_KEY }}
